server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminappDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: admin-app
    version: '@project.version@'